### ISSUE TITLE
admin_password characters

### ISSUE THREAD

**Issue by neilgee** [aaemnnosttv/wp-cli-valet-command#31]
Can't seem to use certain characters or pattern of characters in the password variable when used in `config.yml`

```
valet new:
  admin_user: newadmin
  admin_password: 1$4me&U#2
  admin_email: support@adomain.com
```
The password above won't work.

**Comment by aaemnnosttv** [comment]
With the password provided here, it gets interpreted as `1$4me` (breaking at the `&` for some reason). This appears to be valid YAML, so it's likely due to some internal parsing in WP-CLI, although I can't say for sure.

In any case, the fix is simply to wrap the string in quotes, which is perfectly valid YAML.

```yml
valet new:
  admin_user: newadmin
  admin_password: "1$4me&U#2"
  admin_email: support@adomain.com
```

Works!
